
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button BCarton;

	private global::Gtk.Label Text;

	private global::Gtk.Button BJugar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.BCarton = new global::Gtk.Button();
		this.BCarton.CanFocus = true;
		this.BCarton.Name = "BCarton";
		this.BCarton.UseUnderline = true;
		this.BCarton.Label = global::Mono.Unix.Catalog.GetString("CARTÓN");
		this.hbox2.Add(this.BCarton);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.BCarton]));
		w1.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.Text = new global::Gtk.Label();
		this.Text.WidthRequest = 264;
		this.Text.Name = "Text";
		this.Text.LabelProp = global::Mono.Unix.Catalog.GetString("BINGO");
		this.Text.Justify = ((global::Gtk.Justification)(2));
		this.hbox2.Add(this.Text);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.Text]));
		w2.Position = 1;
		w2.Expand = false;
		this.hbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.BJugar = new global::Gtk.Button();
		this.BJugar.CanFocus = true;
		this.BJugar.Name = "BJugar";
		this.BJugar.UseUnderline = true;
		this.BJugar.Label = global::Mono.Unix.Catalog.GetString("JUGAR");
		this.hbox1.Add(this.BJugar);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BJugar]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 413;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.BCarton.Clicked += new global::System.EventHandler(this.OnBCartonClicked);
		this.BJugar.Clicked += new global::System.EventHandler(this.OnBJugarClicked);
	}
}
