
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label titulo;

	private global::Gtk.HBox hbox1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Entry text;

	private global::Gtk.Button BSaludar;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Entry entry3;

	private global::Gtk.Button BAleatorio;

	private global::Gtk.Button BSalir;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.titulo = new global::Gtk.Label();
		this.titulo.WidthRequest = 22;
		this.titulo.Name = "titulo";
		this.titulo.LabelProp = global::Mono.Unix.Catalog.GetString("Mi primer programa");
		this.titulo.Justify = ((global::Gtk.Justification)(2));
		this.vbox1.Add(this.titulo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.titulo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.text = new global::Gtk.Entry();
		this.text.CanFocus = true;
		this.text.Name = "text";
		this.text.IsEditable = true;
		this.text.InvisibleChar = '•';
		this.hbox2.Add(this.text);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.text]));
		w2.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.BSaludar = new global::Gtk.Button();
		this.BSaludar.WidthRequest = 0;
		this.BSaludar.HeightRequest = 0;
		this.BSaludar.CanFocus = true;
		this.BSaludar.Name = "BSaludar";
		this.BSaludar.UseUnderline = true;
		this.BSaludar.Label = global::Mono.Unix.Catalog.GetString("Saludar");
		this.hbox2.Add(this.BSaludar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.BSaludar]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.hbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
		w4.Position = 0;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = false;
		this.entry3.InvisibleChar = '•';
		this.hbox3.Add(this.entry3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entry3]));
		w6.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.BAleatorio = new global::Gtk.Button();
		this.BAleatorio.CanFocus = true;
		this.BAleatorio.Name = "BAleatorio";
		this.BAleatorio.UseUnderline = true;
		this.BAleatorio.Label = global::Mono.Unix.Catalog.GetString("Aleatorio");
		this.hbox3.Add(this.BAleatorio);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.BAleatorio]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.BSalir = new global::Gtk.Button();
		this.BSalir.CanFocus = true;
		this.BSalir.Name = "BSalir";
		this.BSalir.UseUnderline = true;
		this.BSalir.Label = global::Mono.Unix.Catalog.GetString("SALIR");
		this.hbox3.Add(this.BSalir);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.BSalir]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.BSaludar.Clicked += new global::System.EventHandler(this.OnBSaludarClicked);
		this.BAleatorio.Clicked += new global::System.EventHandler(this.OnBAleatorioClicked);
		this.BSalir.Clicked += new global::System.EventHandler(this.OnBSalirClicked);
	}
}
